
services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Octavo_234
      POSTGRES_DB: authentication
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: node_app
    restart: always
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: BASElogin
      DB_HOST: logindb.cngsycm0ahs7.us-east-1.rds.amazonaws.com
      DB_PORT: 5432
      DB_NAME: authentication
      JWT_SECRET: 2468
      PORT: 3000

volumes:
  pgdata:
